### ISSUE TITLE
functools does not work on python 2.6

### ISSUE THREAD

**Issue by SeyZ** [SeyZ/baboon#60]
```
(baboon)[root@techte ~]# baboon register admin --nosave
Traceback (most recent call last):
  File "/root/virtenvs/baboon/bin/baboon", line 5, in <module>
    pkg_resources.run_script('baboon==0.1', 'baboon')
  File "/root/virtenvs/baboon/lib/python2.6/site-packages/setuptools-0.6c11-py2.6.egg/pkg_resources.py", line 489, in run_script
  File "/root/virtenvs/baboon/lib/python2.6/site-packages/setuptools-0.6c11-py2.6.egg/pkg_resources.py", line 1207, in run_script
  File "/root/virtenvs/baboon/lib/python2.6/site-packages/baboon-0.1-py2.6.egg/EGG-INFO/scripts/baboon", line 4, in <module>
    from baboon.baboon.main import Main
  File "/root/virtenvs/baboon/lib/python2.6/site-packages/baboon-0.1-py2.6.egg/baboon/baboon/main.py", line 6, in <module>
    from baboon.baboon.plugins import *
  File "/root/virtenvs/baboon/lib/python2.6/site-packages/baboon-0.1-py2.6.egg/baboon/baboon/plugins/git/__init__.py", line 6, in <module>
    __import__(module[:-3], locals(), globals())
  File "/root/virtenvs/baboon/lib/python2.6/site-packages/baboon-0.1-py2.6.egg/baboon/baboon/plugins/git/monitor_git.py", line 5, in <module>
    from functools import cmp_to_key
ImportError: cannot import name cmp_to_key
```
